// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdUoXGxso4ciRMlRMSu7IBy4pL3M3rBF0',
    appId: '1:146539937566:web:4d59f49af7a03abf49d30f',
    messagingSenderId: '146539937566',
    projectId: 'pennypal-de604',
    authDomain: 'pennypal-de604.firebaseapp.com',
    storageBucket: 'pennypal-de604.firebasestorage.app',
    measurementId: 'G-L7R5NFLXCN',
    databaseURL: 'https://firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiEnFjPEH_nB3U6AUgnYbVYY3jgP7HzCo',
    appId: '1:146539937566:android:0292c597230b846449d30f',
    messagingSenderId: '146539937566',
    projectId: 'pennypal-de604',
    storageBucket: 'pennypal-de604.firebasestorage.app',
    databaseURL: 'https://firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyQ8zrj_Ss2nCxIQQcHMGsVSODiCjKE8M',
    appId: '1:146539937566:ios:5cc5b3930274392e49d30f',
    messagingSenderId: '146539937566',
    projectId: 'pennypal-de604',
    storageBucket: 'pennypal-de604.firebasestorage.app',
    iosBundleId: 'com.example.pennyPal',
    databaseURL: 'https://firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyQ8zrj_Ss2nCxIQQcHMGsVSODiCjKE8M',
    appId: '1:146539937566:ios:5cc5b3930274392e49d30f',
    messagingSenderId: '146539937566',
    projectId: 'pennypal-de604',
    storageBucket: 'pennypal-de604.firebasestorage.app',
    iosBundleId: 'com.example.pennyPal',
    databaseURL: 'https://firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdUoXGxso4ciRMlRMSu7IBy4pL3M3rBF0',
    appId: '1:146539937566:web:f3e83a61b729a40d49d30f',
    messagingSenderId: '146539937566',
    projectId: 'pennypal-de604',
    authDomain: 'pennypal-de604.firebaseapp.com',
    storageBucket: 'pennypal-de604.firebasestorage.app',
    measurementId: 'G-G2E783HY0H',
    databaseURL: 'https://firebaseio.com',
  );
}
