// File generated by FlutterFire CLI or custom setup.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your PennyPal Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDecB49kk93prHZcac7mdaZ8uGQPl6aJLA',
    appId: '1:655977268911:web:872deae4510a1e7d06765a',
    messagingSenderId: '655977268911',
    projectId: 'pennypal-6ee26',
    authDomain: 'pennypal-6ee26.firebaseapp.com',
    storageBucket: 'pennypal-6ee26.firebasestorage.app',
    measurementId: 'G-SL4WQG0B4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqUnW0DhxKJJQbZCY0dKc23WjrzmYVoVM',
    appId: '1:655977268911:android:1f92d3217880832406765a',
    messagingSenderId: '655977268911',
    projectId: 'pennypal-6ee26',
    storageBucket: 'pennypal-6ee26.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPbW0_jIOGVkeyk-GYQ2ABljAaxhbPjuk',
    appId: '1:655977268911:ios:2eb4b4a04838996406765a',
    messagingSenderId: '655977268911',
    projectId: 'pennypal-6ee26',
    storageBucket: 'pennypal-6ee26.firebasestorage.app',
    iosBundleId: 'com.example.pennyPal',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:123456789012:ios:abcdef123456',
    messagingSenderId: '123456789012',
    projectId: 'pennypal-app',
    storageBucket: 'pennypal-app.appspot.com',
    iosBundleId: 'com.example.pennyPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDecB49kk93prHZcac7mdaZ8uGQPl6aJLA',
    appId: '1:655977268911:web:253e74a94834b13006765a',
    messagingSenderId: '655977268911',
    projectId: 'pennypal-6ee26',
    authDomain: 'pennypal-6ee26.firebaseapp.com',
    storageBucket: 'pennypal-6ee26.firebasestorage.app',
    measurementId: 'G-1ZLK8P001R',
  );
}
